joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
  gains:
    joint1: {p: 100.0, d: 10.0, i: 1.0}
    joint2: {p: 100.0, d: 10.0, i: 1.0}
    joint3: {p: 100.0, d: 10.0, i: 1.0}

